name: hrapp
description: A new Flutter application.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.0.1
  custom_searchable_dropdown:
  universal_platform: ^1.0.0+1
  rxdart: ^0.27.2
  new_version_plus:
  jwt_decode: ^0.3.1
  intl_utils:
  url_launcher:
  flutter_spinkit: ^5.1.0
  flutter_datetime_picker: ^1.5.1
  firebase_auth:
  intl:
  fluttertoast: ^8.0.8
  animated_splash_screen: ^1.2.0
  http_parser: ^4.0.0
  firebase_core:
  http: ^0.13.4
  autocomplete_textfield:
  table_calendar: ^3.0.6
  image_picker:
  flutter_screenutil: ^5.0.0+2
  google_fonts: ^4.0.3
  flutter_time_picker_spinner:
  provider: ^6.0.0
  json_serializable:
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  path_provider:
  transitions_page: ^1.0.0
  custom_progress_button: ^1.0.2
  form_field_validator: ^1.1.0
  image_loader: ^1.0.7
  simple_shared_pref: ^1.0.2
  shrink_sidemenu: ^2.0.0+1-null-safety
  signalr_core: ^1.1.1
  permission_handler: ^10.2.0
  animated: ^2.0.0
  date_utils:
  keyboard_service: ^2.0.0
  flutter_custom_tabs: ^1.0.3
  local_auth:
  pull_to_refresh:
  in_app_update:
  #  flutter_webview_plugin:
  sentry_flutter:
  #  firebase_analytics: ^5.0.2
  #  carousel_pro_nullsafety: ^1.0.2
  flutter_staggered_grid_view:
  persistent_bottom_nav_bar:
  percent_indicator: ^4.2.3
  bottom_dialog: ^1.0.3
  notification_permissions:
  carousel_slider: ^4.0.0
  flutter_app_badger:
  liquid_pull_to_refresh: ^3.0.0
  fast_rsa: ^3.0.3
  progress_dialog_null_safe: ^1.0.6
  flutter_animated_dialog: ^2.0.1
  get:
  modal_progress_hud_nsn:




dev_dependencies:

  #  flutter_test:
  #    sdk: flutter
  build_runner:
  retrofit_generator:
  flutter_launcher_icons: ^0.11.0
  #  flutter pub run flutter_launcher_icons:main
  flutter_native_splash: ^2.2.0+1
  #  flutter pub run flutter_native_splash:create
  flutter_app_name: ^0.1.0
#    flutter pub run flutter_app_name

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/transAndroid.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  # fonts:

flutter_intl:
  enabled: true

flutter_native_splash:
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true
flutter_app_name:
  name: "hrapp"